language: objective-c
os: osx
osx_image: xcode9.4
sudo: required
python: '3.6'
git:
  depth: 1
branches:
  only:
  - master

env:
  global:
  - BUILD_VERSION="0.1.0"

before_install:
- brew install python3
- python3 -m venv venv
- source venv/bin/activate
- python3 -m pip install -U pip
- python3 -m pip install PyInstaller>=3.6

install:
- wget https://github.com/namuan/dev-rider/archive/${BUILD_VERSION}.tar.gz -O ./devrider.tar.gz
- tar -xvf ./devrider.tar.gz
- mv dev-rider-${BUILD_VERSION}/* .
- rm -rf devrider.tar.gz dev-rider-${BUILD_VERSION}
- python3 -m pip install -r requirements/base.txt

script:
- make clean package
- zip "${TRAVIS_BUILD_DIR}"/devrider.zip dist/devrider.app
- echo "Done!"

notifications:
  email: false

before_deploy:
- git config --local user.name "namuan"
- git remote set-url origin https://namuan:${GITHUB_TOKEN}@github.com/namuan/dev-rider-osx.git
- git push origin :refs/tags/${BUILD_VERSION}
- git tag -f -am v${BUILD_VERSION} ${BUILD_VERSION}

deploy:
  provider: releases
  api-key: "${GITHUB_TOKEN}"
  file: "${TRAVIS_BUILD_DIR}/devrider.zip"
  overwrite: true
  skip_cleanup: true
  on:
    repo: namuan/dev-rider-osx